### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by scjuly19**
- Added text utilities.
- Added modal component.
- Added navigation header component.

### CODE REVIEW

**Review by ramalingaa — APPROVED** [review]
Code looks clean

**Comment by shahbazibnafzal** [comment]
1. Modal is allowing the page scroll, you might consider disabling the scroll when modal is open.
2. Please include JS code snippet for opening and closing the modal.
3. Visibility of the modal is very low in dark mode.

image

**Comment by scjuly19** [comment]
@shahbaz4595  I have fixed all the issues mentioned by you, please consider reviewing them again.

**Review by shahbazibnafzal — APPROVED** [review]
Looks good Sakshi, You can merge it.

**Pull request merged**
