### PR TITLE
Feat: Added badges and button components

### PR DESCRIPTION
**Pull request by scjuly19**
- Added badge component with different status and icons
- Added buttons with icons, links and primary variants.

### CODE REVIEW

**Review by manish591 — APPROVED** [review]
Your code is looking neat and clean.

**Comment by surajmore98** [comment]
some classes don't have space between classname ane curly bracket.
otherwise looks all good.

**Review by surajmore98 — COMMENTED** [review]
some classes don't have space between classname ane curly bracket.
otherwise looks all good.

**Comment by shahbazibnafzal** [comment]
Looks good to me.

**Review by shahbazibnafzal — APPROVED** [review]
Looks good

**Pull request merged**
